note: Service Information
nodes:
  init:
    type: callback
    client:
      name: save_qualification_answer
      args:
        - message
        - qualification_question
      return:
    go_to:
      data:
      cases: []
      default:
        to: service
        step: loop_qualification_questions
  collect_services:
    type: callback
    client:
      name: get_services
      args: []
      return: services
    go_to:
      data:
      cases: []
      default:
        to: service
        step: classify_service
  classify_service:
    type: analyze
    client:
      prompt: |
        Goal: Analyze chat history and classify service
        Output schema:
        ```json
        {
          "trade": string, // electronical | plumbing | etc...
          "serviceable_type": string // Car Chargers | Tankless Wh | Sewer Drain | etc...
          "service_type": string // Replace | Inspection | Connect | etc...
          "can_not_find": boolean // It's true if you can't find service from list
        }
        ```

        The service list:
        $services

        Output only json format code. Any explanations or plaintext are not allowed.
      return: service
    go_to:
      data: service
      cases:
        - name: can_not_find
          value: true
          to: service
          step: not_support_service
      default:
        to: service
        step: check_service
  check_service:
    type: callback
    client:
      name: check_service
      args:
        - service
      return: service_check_result
    go_to:
      data: service_check_result
      cases:
        - name: support
          value: support
          to: service
          step: loop_qualification_questions
        - name: support
          value: some_support
          to: service
          # step: ask_confirm_disqualification
          step: not_support_service
        - name: support
          value: not_support
          to: service
          step: not_support_service
  not_support_service:
    type: process
    client:
      prompt: |
        Base text
        """
        Sorry, but we don't support service what you want. Can I help you for other thing? If you troubling because of other thing, please let me know. We're trying to help you.
        """
        or
        """
        unfortunately, we don't service what you want. But I think we can help you in other things. Please let me know if you need help.
        """

        Update this assistant message more friendly and reasonably.

        Output ONLY updated text. (no explanations, no extra text, no code format)
    go_to:
      data:
      cases: []
      default:
        to: extra
        step: handle_cancel
  loop_qualification_questions:
    type: callback
    client:
      name: get_qualification_question
      args: []
      return: qualification_question
    go_to:
      data: qualification_question
      cases:
        - name: answered
          value: false
          to: service
          step: ask_qualification_question
        - name: answered
          value: null
          to: service
          step: finish_agent
      default:
        to: service
        step: finish_agent
  ask_qualification_question:
    type: process
    client:
      prompt: |
        You are an assistant to collect answers about qualification questions.
        This is current question need to collect answer.
        $qualification_question

        Please ask question and collect answer.
        According to chat history:
        - If first asking, mention the service is supportable, and to ensure more details you want to get answers about qualification questions.
        - After that, ask questios with prefix like Next, Also, or other words.
        - The keep the original qualification question. Don't update question.

        Important: I need assistant asking message only.
        Output ONLY assistant message. (no explanations, no extra text, no code format)
    go_to:
      data:
      cases: []
      default:
        finished: true
        to: service
        step: init
  finish_agent:
    type: callback
    client:
      name: finish_service_agent
      args: []
      return:
    go_to:
      data:
      cases: []
      default:
        to: service
        step: output_thanks_message
  output_thanks_message:
    type: process
    client:
      prompt: |
        Output thanks message about answering for qualification questions.
        And mention it will be helpful to determine your worries and fix them.
        Only output thanks message.

        Output ONLY assistant message. (no explanations, no extra text, no code format)
    go_to:
      data:
      cases: []
      default:
        to: service
        step: go_to_other_agent
  go_to_other_agent:
    type: callback
    client:
      name: get_customer_status
      args: []
      return: customer_status
    go_to:
      data: customer_status
      cases:
        - name: greeting
          value: false
          to: greeting
          step: fetch_contact_information
        - name: service_address
          value: false
          to: greeting
          step: go_to_addresses
        - name: property
          value: false
          to: property
          step: init
        - name: dispatch
          value: false
          to: dispatch
          step: init
      default:
        to: extra
        step: handle_success 