note: Service Information
nodes:
  init:
    type: analyze
    client:
      prompt: |
      return:
    go_to:
      data:
      cases: []
      defualt:
        to: service
        step: collect_services
  collect_services:
    type: callback
    client:
      name: get_services
      args: []
      return: services
    go_to:
      data:
      cases: []
      default:
        to: service
        step: classify_service
  classify_service:
    type: analyze
    client:
      prompt: |
        Goal: Analyze chat history and classify service
        Output schema:
        ```json
        {
          "trade": string, // electronical | plumbing | etc...
          "serviceable_type": string // Car Chargers | Tankless Wh | Sewer Drain | etc...
          "service_type": string // Replace | Inspection | Connect | etc...
          "can_not_find": boolean // It's true if you can't find service from list
        }
        ```

        The service list:
        $services

        Output only json format code. Any explanations or plaintext are not allowed.
      return: service
    go_to:
      data: service
      cases:
        - name: can_not_find
          value: true
          to: service
          step: not_support_service
      default:
        to: service
        step: check_service
  check_service:
    type: callback
    client:
      name: check_service
      args:
        - service
      return: service_check_result
    go_to:
      data: service_check_result
      cases:
        - name: support
          value: support
          to: service
          step: ask_qualification_questions
        - name: support
          value: some_support
          to: service
          step: ask_confirm_disqualification
        - name: support
          value: not_support
          to: service
          step: not_support_service
  not_support_service:
    type: process
    client:
      prompt: |
        Base text
        """
        Sorry, but we don't support service what you want. Can I help you for other thing? If you troubling because of other thing, please let me know. We're trying to help you.
        """
        or
        """
        unfortunately, we don't service what you want. But I think we can help you in other things. Please let me know if you need help.
        """

        Update this assistant message more friendly and reasonably.

        Output ONLY updated text. (no explanations, no extra text, no code format)
    go_to:
      data:
      cases: []
      default:
        finished: true
        to: intent
        step: init